#!/bin/bash

if [ $# -ne 1 ] ; then 
	echo 'Error: geolocate takes only one argument - an ip address or url.'
else
	CURL="/usr/bin/curl"
	RVMHTTP="freegeoip.net/csv/$1"
	CURLARGS="-s"

	# you can store the result in a variable
	response="$($CURL $CURLARGS $RVMHTTP)"

	if [ ${#response} -eq 0 ] ; then
		echo "Error: Not able to connect to freegeoip.net"
	elif [ "$response" == "404 page not found" ] ; then
		echo "Error: Invalid argument - '$1' not found on freegeoip.net"
	else
		IFS=',' read -ra VALS <<< "$response"

		# get length of an array
		arraylength=${#VALS[@]}

		# use for loop to read all values and indexes, replace empty things with N/A
		for (( i=0; i<${arraylength}; i++ ));
		do
			if [ ${#VALS[$i]} -eq 0 ] ; then
				VALS[$i]="N/A"
			fi
		done

		echo "IP Address: ${VALS[0]}"
		echo "Location Name: ${VALS[5]}, ${VALS[3]}, ${VALS[2]}"
		echo "Lat, Long: (${VALS[8]}, ${VALS[9]})"
	fi
fi
