#!/bin/bash

if [ $# -ne 1 ] ; then
	echo 'Error: geolocate takes only one argument - an ip address or url.'
else
	CURL="/usr/bin/curl"
	RVMHTTP="http://ip-api.com/csv/$1?fields=country,regionName,city,lat,lon,query"
	CURLARGS="-s"

	# you can store the result in a variable
	response="$($CURL $CURLARGS $RVMHTTP)"

	if [ ${#response} -eq 0 ] ; then
		echo "Error: Not able to connect to ip-api.com"
	elif [ "$response" == "404 page not found" ] ; then
		echo "Error: Invalid argument - '$1' not found on ip-api.com"
	else
		IFS=',' read -ra VALS <<< "$response"

		# get length of an array
		arraylength=${#VALS[@]}

		# use for loop to read all values and indexes, replace empty things with N/A
		for (( i=0; i<${arraylength}; i++ ));
		do
			if [ ${#VALS[$i]} -eq 0 ] ; then
				VALS[$i]="N/A"
			fi
		done

		echo "IP Address: ${VALS[5]}"
		echo "Location Name: ${VALS[2]}, ${VALS[1]}, ${VALS[0]}"
		echo "Lat, Long: http://www.google.com/maps/search/?api=1&query=${VALS[3]},${VALS[4]}"
	fi
fi
